name: Deploy to GitHub Pages

on:
  push:
    branches: [ frontend ]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          sparse-checkout: |
            student-module-frontend
          sparse-checkout-cone-mode: false
      
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "18.17.0"
          cache: 'npm'
          cache-dependency-path: './student-module-frontend/package-lock.json'
      
      - name: Install dependencies
        working-directory: ./student-module-frontend
        run: npm install
        
      - name: Build
        working-directory: ./student-module-frontend
        run: npm run build
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./student-module-frontend/out

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2