services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "3000:3000"
    command: npx nodemon src/server.js
    env_file:
      - .env
    depends_on:
      - ai-backend
  
  ai-backend:
    build: ./ai-backend
    volumes:
      - ./ai-backend:/app
    ports:
      - "8080:8080"
    command: uvicorn main:app --host 0.0.0.0 --port 8080 --reload
    env_file:
      - .env
    