name: Deploy to GitHub Pages

on:
  push:
    branches: [ frontend ]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: student-module-frontend
        
    steps:
      - uses: actions/checkout@v4
        with:
          ref: frontend
          
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: 'npm'
          cache-dependency-path: student-module-frontend/package-lock.json
      
      - name: Install dependencies
        run: npm ci
        
      - name: Build and Export
        run: |
          npm run build
          touch out/.nojekyll
        
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: student-module-frontend/out

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
